CREATE TABLE restaurant.violationcodeskey
(
    Violation_Number int(11),
    Violation_Description varchar(200),
    Violation_Category varchar(200)
);
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (0, 'Kongfu Panda', 'Approved Source');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (1, 'Correct response to questions', 'Demonstration of knowledge');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (2, 'Management awareness; policy present', 'Employee Health');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (3, 'Proper use of restriction and exclusion', 'Employee Health');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (4, 'Proper eating, tasting, drinking, or tobacco use', 'Good Hygienic Practices');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (5, 'No discharge from eyes, nose and mouth', 'Good Hygienic Practices');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (6, 'Hands clean and properly washed', 'Preventing Contamination by Hands');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (7, 'No bare hand contact with ready-to-eat foods or approved', 'Preventing Contamination by Hands');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (8, 'Adequate handwashing sinks properly supplied and accessible', 'Preventing Contamination by Hands');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (9, 'Food obtained from approved source', 'Approved Source');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (10, 'Food received at proper temperature', 'Approved Source');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (11, 'Food in good condition, safe, unadulterated', 'Approved Source');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (12, 'Required records available: shellstock tags, parasite destruction', 'Approved Source');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (13, 'Food separated and protected', 'Protection from Contamination');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (14, 'Food-contact surfaces: cleaned & sanitized', 'Protection from Contamination');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (15, 'Proper disposition of returned, previously served, reconditioned, and unsafe food', 'Protection from Contamination');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (16, 'Proper cooking time and temperatures', 'Potentially Hazardous Food (TCS Food)');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (17, 'Proper reheating procedures for hot holding', 'Potentially Hazardous Food (TCS Food)');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (18, 'Proper cooling time & temperatures', 'Potentially Hazardous Food (TCS Food)');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (19, 'Proper hot holding temperatures', 'Potentially Hazardous Food (TCS Food)');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (20, 'Proper cold holding temperatures', 'Potentially Hazardous Food (TCS Food)');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (21, 'Proper date marking & disposition', 'Potentially Hazardous Food (TCS Food)');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (22, 'Time as a public health control: procedures & records', 'Potentially Hazardous Food (TCS Food)');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (23, 'Consumer advisory provided for raw or undercooked foods', 'Consumer Advisory');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (24, 'Pasteurized foods used; prohibited foods not offered', 'Highly Susceptible Populations');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (25, 'Food additives: approved & properly used', 'Chemical');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (26, 'Toxic substances properly identified, stored, used', 'Chemical');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (27, 'Compliance with variance, specialized process, and HACCP plan', 'Conformance with Approved Procedures');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (28, 'Pasteurized eggs used where required', 'Safe Food and Water');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (29, 'Water & Ice approved source', 'Safe Food and Water');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (30, 'Variance obtained for specialized processing methods', 'Safe Food and Water');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (31, 'Proper cooling methods used; adequate equipment for temperature control', 'Food Temperature Control');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (32, 'Plant food properly cooked for hot holding', 'Food Temperature Control');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (33, 'Approved thawing methods used', 'Food Temperature Control');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (34, 'Thermometers provided & accurate', 'Food Temperature Control');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (35, 'Food properly labeled; original container', 'Food Identification');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (36, 'Insects, rodents, & animals not present', 'Prevention of Food Contamination');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (37, 'Contamination prevented during food preparation, storage, & display', 'Prevention of Food Contamination');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (38, 'Personal cleanliness', 'Prevention of Food Contamination');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (39, 'Wiping cloths: properly used & stored', 'Prevention of Food Contamination');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (40, 'Washing fruits & vegetables', 'Prevention of Food Contamination');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (41, 'In-use utensils: properly stored', 'Proper Use of Utensils');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (42, 'Utensils, equipment & linens: properly stored, dried, & handled', 'Proper Use of Utensils');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (43, 'Single-use/single-service articles: properly stored & used', 'Proper Use of Utensils');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (44, 'Gloves used properly', 'Proper Use of Utensils');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (45, 'Food and nonfood-contact surfaces cleanable, properly designed, constructed, & used', 'Utensils, Equipment, and Vending');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (46, 'Warewashing facilities: installed, maintained, & used; test strips', 'Utensils, Equipment, and Vending');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (47, 'Nonfood-contact surfaces clean', 'Utensils, Equipment, and Vending');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (48, 'Hot & cold water available; adequate pressure', 'Physical Facilites');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (49, 'Plumbing installed; proper backflow devices', 'Physical Facilites');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (50, 'Sewage & waste water properly disposed', 'Physical Facilites');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (51, 'Toilet facilities: properly constructed, supplied, & cleaned', 'Physical Facilites');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (52, 'Garbage & refuse properly disposed, facilities maintained', 'Physical Facilites');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (53, 'Physical facilities: installed, maintained, & clean', 'Physical Facilites');
INSERT INTO restaurant.violationcodeskey (Violation_Number, Violation_Description, Violation_Category) VALUES (54, 'Adequate ventilation & lighting: designated areas used', 'Physical Facilites');